### ISSUE TITLE
Merge into original

### ISSUE THREAD

**Issue by dougaitken** [lerrua/remote-jobs-brazil#108]
Hey! 

I got linked to this by a colleague, love the idea. 

I maintain the main list at `https://github.com/remoteintech/remote-jobs` and that list is meant to be worldwide, not US centric (I live in Scotland, so it _won't_ become US centric). 

I'd love it if this list was merged into my list so we have everything in one place, I launched a website for my repository today - https://remoteintech.company

Thanks!

**Comment by lerrua** [comment]
Hi @dougaitken!

Thank you so much for opened this issue and I really like the "merge" idea.
But we have a problem before do that and maybe you can help me to find a solution.

Today my repository have a "brazilian-friendly" feature, that's why I have a section called "_Worldwide companies that hire Brazilians to work remotely_", actually to support brazilians find companies which language and time zone is not a problem, so probably companies in this section have some Brazilian  hired.

Briefly in my case, it's not enough to have the "region" column in the list, but rather something that can tell me that that company is "brazilian-friendly".

**Comment by dougaitken** [comment]
Ah, interesting! I can see that being something I could cover by expanding the `region` section. At Automattic, we have quite a few Brazilian colleagues, so sometimes worldwide companies hire for localized support.

I'll give it some thought and let you know. Even linking out to here under a "localized support" heading could work?

**Comment by drFabio** [comment]
@dougaitken How your repo relates to this one https://github.com/lukasz-madon/awesome-remote-job#job-boards ? Are you trying to merge with it as well?

**Comment by andrealmar** [comment]
Hi all. I personally believe that it would be better to remain with the "brazilian-friendly" feature as @lerrua said "Worldwide companies that hire Brazilians to work remotely".

If the intention is to have a generic job board like many others already out there, this repo would be just another one...

**Comment by dougaitken** [comment]
@drFabio that is a list of lists and information. my repo will another source of information and listing _companies_ rather than listing _jobs_

**Comment by drFabio** [comment]
got it @dougaitken
